---
title: "Cell-type specific enrichment analysis"
subtitle: Dexamethasone-Stimulated Human Array Project
output:
  html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r include = F}
library(data.table)
library(dplyr)
library(ggplot2)
library(corrplot)
library(factoextra)
library(viridis)
```

Load groups

```{r}
setwd("~/bio/code/mpip/dex-stim-human-array/")
# opposite.fc.df <- fread("output/data/integrative/matrixEQTL/meqtls/meqtl_parallel_and_opposite_fc_groups/meqtl_opposite_fc_gr_df.csv")
# 
# opposite.fc.cpg.ids <- opposite.fc.df$CpG_ID %>% unique()
# 
# parallel.fc.delta.df <- fread("~/bio/code/mpip/dex-stim-human-array/output/data/integrative/matrixEQTL/meqtls/meqtl_parallel_and_opposite_fc_groups/meqtl_parallel_fc_gr_delta_df.csv")
# 
# parallel.fc.veh.dex.df <- fread("~/bio/code/mpip/dex-stim-human-array/output/data/integrative/matrixEQTL/meqtls/meqtl_parallel_and_opposite_fc_groups/meqtl_parallel_fc_gr_veh_dex_df.csv")

opposite.fc.cpg.ids     <- fread("output/data/integrative/matrixEQTL/meqtls/meqtl_parallel_and_opposite_fc_groups/meqtl_opposite_fc_gr_cpg_list.csv")
parallel.fc.delta.ids   <- fread("output/data/integrative/matrixEQTL/meqtls/meqtl_parallel_and_opposite_fc_groups/meqtl_parallel_fc_gr_delta_cpg_lst.csv")
parallel.fc.veh.dex.ids <- fread("output/data/integrative/matrixEQTL/meqtls/meqtl_parallel_and_opposite_fc_groups/meqtl_parallel_fc_gr_veh_dex_cpg_lst.csv")
```

Read TCA models

```{r}
fn.lst  <- list.files("~/bio/code/mpip/dex-stim-human-array/output/data/integrative/cell_type_enrichment", 
                     pattern = "*RDS", full.names = TRUE)

tca.mdls <- lapply(fn.lst[-3], readRDS)
```

```{r}
tca.mdl   <- lapply(tca.mdls, function(mdl) mdl$tca_mdl)
tca.mu.df <- lapply(tca.mdl, function(mdl) mdl$mus_hat)
tca.mu.df <- do.call(rbind, tca.mu.df) %>% data.frame() %>% setDT(keep.rownames = T) # mean of each BCC type in each CpG

dim(tca.mu.df)
```

```{r}
tcareg.mdl     <- lapply(tca.mdls, function(mdl) mdl$tcareg_mdl)
tcareg.pval.df <- lapply(tcareg.mdl, function(mdl) mdl$pvals)
tcareg.pval.df <- do.call(rbind, tcareg.pval.df) %>% data.frame() %>% setDT(keep.rownames = T) # mean of each BCC type in each CpG

dim(tcareg.pval.df)

head(tcareg.pval.df)
```

```{r}
tcareg.sign.pval.df <- tcareg.pval.df %>% reshape2::melt() %>% setDT()
colnames(tcareg.sign.pval.df) <- c("CpG_ID", "Type", "pval")
tcareg.sign.pval.df <- tcareg.sign.pval.df[pval <= 0.05]

tcareg.sign.pval.df[CpG_ID %in% opposite.fc.cpg.ids$CpG_ID, Model := "opposite_fc"]
tcareg.sign.pval.df[CpG_ID %in% parallel.fc.delta.ids$CpG_ID, Model := "parallel_fc_delta"]
tcareg.sign.pval.df[CpG_ID %in% parallel.fc.veh.dex.ids$CpG_ID, Model := "parallel_fc_veh_dex"]

tcareg.sign.pval.df <- na.omit(tcareg.sign.pval.df)

tca.mu.sign.df <- tca.mu.df[rn %in% tcareg.sign.pval.df$CpG_ID]
tca.mu.sign.df <- tca.mu.sign.df %>% reshape2::melt() 
colnames(tca.mu.sign.df) <- c("CpG_ID", "Type", "tca_mu_val")

tca.sign.mu.pval.df <- left_join(tcareg.sign.pval.df, tca.mu.sign.df)

dim(tca.sign.mu.pval.df)
head(tca.sign.mu.pval.df)
```

```{r}
tca.sign.mu.median.df <- aggregate(tca_mu_val ~ Model + Type, tca.sign.mu.pval.df, median)
(tca.sign.mu.median.df)

ggplot(tca.sign.mu.median.df, aes(y = tca_mu_val, x = Model, fill = Model)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  scale_fill_viridis(discrete = TRUE, alpha = 0.7, option = "D") +
  facet_wrap(~ Type, ncol = 12) +
  labs(title = " ", y = "Median of estimates for the mean of each blood cell type in each CpG", x = " ") + 
  theme(legend.position = "bottom", 
        legend.title = element_blank(),
        panel.grid.major = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 10),
        axis.title = element_text(size = 11),
        axis.title.x = element_blank(),
        axis.text.x =  element_blank())
```

```{r eval = F, include = F}

# Chromosome 22

tca.mdl.chr.22 <- tca.mdl[[12]]

dim(tca.mdl.chr.22$tca_mdl$gammas_hat_pvals)

dim(tca.mdl.chr.22$W)
dim(tca.mdl.chr.22$mus_hat)
dim(tca.mdl.chr.22$sigmas_hat)
dim(tca.mdl.chr.22$tau_hat)
dim(tca.mdl.chr.22$gammas_hat)
dim(tca.mdl.chr.22$gammas_hat_pvals)
dim(tca.mdl.chr.22$gammas_hat_pvals.joint)

tca.mdl.chr.22$gammas_hat_pvals[1:10, 1:8]
tca.mdl.chr.22$gammas_hat_pvals.joint[1:10,]
```

```{r eval = F, include = F}
# Chromosome 22

tca.mdl.chr.22 <- tca.mdl[[12]]

head(tca.mdl.chr.22$tcareg_mdl$

dim(tca.mdl.chr.22$W)
dim(tca.mdl.chr.22$mus_hat)
dim(tca.mdl.chr.22$sigmas_hat)
dim(tca.mdl.chr.22$tau_hat)
dim(tca.mdl.chr.22$gammas_hat)
dim(tca.mdl.chr.22$gammas_hat_pvals)
dim(tca.mdl.chr.22$gammas_hat_pvals.joint)

tca.mdl.chr.22$gammas_hat_pvals[1:10, 1:8]
tca.mdl.chr.22$gammas_hat_pvals.joint[1:10,]
```

```{r eval = F}
x <- lapply(tca.mdl, function(mdl){
  pval.joint <- mdl$gammas_hat_pvals.joint[, "Age"]
  pvals.marg_cond <- mdl$gammas_hat_pvals[, paste(colnames(mdl$W), ".Age", sep = "")]
  hits.joint <- names(which(pval.joint < 0.05/nrow(mdl$X)))
})
```

```{r}
tca.opposite.mu.df <- data.frame(tca.mu.df[rownames(tca.mu.df) %in% opposite.fc.cpg.ids$CpG_ID,],
                                 Model = "opposite_fc")

head(tca.opposite.mu.df)
summary(tca.opposite.mu.df)
```
```{r}
tca.parallel.delta.mu.df <- data.frame(tca.mu.df[rownames(tca.mu.df) %in% parallel.fc.delta.ids$CpG_ID,],
                                       Model = "parallel_fc_delta")

head(tca.parallel.delta.mu.df)
summary(tca.parallel.delta.mu.df)
```

```{r}
tca.parallel.veh.dex.mu.df <- data.frame(tca.mu.df[rownames(tca.mu.df) %in% parallel.fc.veh.dex.ids$CpG_ID,],
                                         Model = "parallel_fc_veh_dex")

head(tca.parallel.veh.dex.mu.df)
summary(tca.parallel.veh.dex.mu.df)
```

```{r}
tca.mu.df <- rbind(tca.opposite.mu.df,
                   tca.parallel.delta.mu.df,
                   tca.parallel.veh.dex.mu.df)

tca.mu.df[["CpG_ID"]] <- rownames(tca.mu.df)


tca.mu.median.df <- aggregate(tca.mu.df[, 1:12], list(tca.mu.df$Model), median)
head(tca.mu.median.df)

melt.df   <- tca.mu.median.df %>% reshape2::melt() 
colnames(melt.df) <- c("Model", "Type", "value")

ggplot(melt.df, aes(y = value, x = Model, fill = Model)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  scale_fill_viridis(discrete = TRUE, alpha = 0.7, option = "D") +
  facet_wrap(~ Type, ncol = 12) +
  labs(title = " ", y = "Median of estimates for the mean of each blood cell type in each CpG", x = " ") + 
  theme(legend.position = "bottom", 
        legend.title = element_blank(),
        panel.grid.major = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 10),
        axis.title = element_text(size = 11),
        axis.title.x = element_blank(),
        axis.text.x =  element_blank())
```


```{r  out.width = "95%", fig.cap = "Box-plots showing distribution of estimates for the mean of each blood cell type in each CpG", incldue = T, eval = T}

tca.mu.df <- rbind(tca.opposite.mu.df,
                   tca.parallel.delta.mu.df,
                   tca.parallel.veh.dex.mu.df)

tca.mu.df[["CpG_ID"]] <- rownames(tca.mu.df)

melt.df   <- tca.mu.df %>% reshape2::melt(id.vars = c("CpG_ID", "Model")) 

ggplot(melt.df, aes(y = value, x = Model, fill = variable)) +
  geom_boxplot() +
  scale_fill_viridis(discrete = TRUE, alpha = 0.3, option = "C") +
  labs(title = " ", y = "Mean estimates", x = " ") + 
  facet_wrap(~ variable, ncol = 6, nrow = 2) +
  theme(legend.position = "none", 
        legend.title = element_blank(),
        panel.grid.major = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 10),
        axis.title = element_text(size = 8),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 25, hjust = 0.5))
```

```{r boxplot, out.width = "95%", fig.cap = "Box-plots showing distribution of estimates for the mean of each blood cell type in each CpG", incldue = T, eval = T}

ggplot(melt.df[melt.df$Model == "opposite_fc",], aes(y = value, x = variable, fill = variable)) +
  geom_boxplot() +
  scale_fill_viridis(discrete = TRUE, alpha = 0.3, option = "C") +
  labs(title = " ", y = "Mean estimates, opposite FC", x = " ") + 
  theme(legend.position = "none", 
        legend.title = element_blank(),
        panel.grid.major = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 10),
        axis.title = element_text(size = 8),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 25, hjust = 0.5))
```

```{r out.width = "95%", fig.cap = "Box-plots showing distribution of estimates for the mean of each blood cell type in each CpG", incldue = T, eval = T}

ggplot(melt.df[melt.df$Model == "parallel_fc_delta",], aes(y = value, x = variable, fill = variable)) +
  geom_boxplot() +
  scale_fill_viridis(discrete = TRUE, alpha = 0.3, option = "C") +
  labs(title = " ", y = "Mean estimates, parallel FC delta", x = " ") + 
  theme(legend.position = "none", 
        legend.title = element_blank(),
        panel.grid.major = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 10),
        axis.title = element_text(size = 8),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 25, hjust = 0.5))
```

```{r out.width = "95%", fig.cap = "Box-plots showing distribution of estimates for the mean of each blood cell type in each CpG", incldue = T, eval = T}

ggplot(melt.df[melt.df$Model == "parallel_fc_veh_dex",], aes(y = value, x = variable, fill = variable)) +
  geom_boxplot() +
  scale_fill_viridis(discrete = TRUE, alpha = 0.3, option = "C") +
  labs(title = " ", y = "Mean estimates, parallel FC veh + dex", x = " ") + 
  theme(legend.position = "none", 
        legend.title = element_blank(),
        panel.grid.major = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 10),
        axis.title = element_text(size = 8),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 25, hjust = 0.5))
```