---
title: "Cell-type specific enrichment analysis"
subtitle: "Dexamethasone-Stimulated Human Array Project"
output:
  html_notebook
editor_options:
  chunk_output_type: inline
---

```{r, warning=FALSE, message=FALSE}
library(data.table)
library(dplyr)
library(ggplot2)
library(corrplot)
library(factoextra)
library(viridis)
```

Load groups

```{r}
opposite.fc.cpg.ids     <- fread("~/bio/code/mpip/dex-stim-human-array/output/data/integrative/matrixEQTL/meqtls/meqtl_parallel_and_opposite_fc_groups/meqtl_opposite_fc_gr_cpg_list.csv")
parallel.fc.delta.ids   <- fread("~/bio/code/mpip/dex-stim-human-array/output/data/integrative/matrixEQTL/meqtls/meqtl_parallel_and_opposite_fc_groups/meqtl_parallel_fc_gr_delta_cpg_lst.csv")
parallel.fc.veh.dex.ids <- fread("~/bio/code/mpip/dex-stim-human-array/output/data/integrative/matrixEQTL/meqtls/meqtl_parallel_and_opposite_fc_groups/meqtl_parallel_fc_gr_veh_dex_cpg_lst.csv")
```

```{r}
pval.veh.fn <- "~/bio/code/mpip/dex-stim-human-array/output/data/integrative/cell_type_enrichment/dnam_cell_type_enrichment_pvals_veh.csv"
pval.veh.df <- fread(pval.veh.fn)

dim(pval.veh.df)

pval.veh.bcc.df <- pval.veh.df[, 1:13]

head(pval.veh.bcc.df)
```

```{r}
fdr.bcc.df <- matrix(p.adjust(as.vector(as.matrix(pval.veh.bcc.df[, 2:13])), method='fdr'), 
                     ncol=12) %>%
  data.frame()

fdr.bcc.df <- cbind(pval.veh.bcc.df$CpG_ID, fdr.bcc.df)
colnames(fdr.bcc.df) <- colnames(pval.veh.bcc.df)
```

```{r}
sign.pval.df <- fdr.bcc.df %>% reshape2::melt(measure.vars = colnames(fdr.bcc.df)[2:13]) %>% setDT()
colnames(sign.pval.df) <- c("CpG_ID", "Type", "fdr")
sign.pval.df <- sign.pval.df[fdr <= 0.05]

sign.pval.df[CpG_ID %in% opposite.fc.cpg.ids$CpG_ID, Model := "opposite_fc"]
sign.pval.df[CpG_ID %in% parallel.fc.delta.ids$CpG_ID, Model := "parallel_fc_delta"]
sign.pval.df[CpG_ID %in% parallel.fc.veh.dex.ids$CpG_ID, Model := "parallel_fc_veh_dex"] 

sign.pval.df <- na.omit(sign.pval.df)
sign.pval.df
```

```{r fig.width = 7, fig.height = 4}
cbPalette <- c( "#0072B2", "#009E73", "#E69F00", "#F0E442", "#D55E00", "#CC79A7", "#56B4E9", "#999999")

ggplot(sign.pval.df, aes(x = Type, fill = Model)) +
  facet_wrap(~ Model, nrow = 3, scales = "free") +
  geom_histogram(stat = "count", alpha = 1, position = "dodge") +
  #  geom_density(alpha = 0.2, aes(color = Model)) + 
  theme(legend.position = "bottom", # c(0.9, 0.9), 
        legend.title = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.background = element_blank(),
        plot.title = element_text(size = 8), 
        axis.title = element_text(size = 8)) + 
  labs(title = "Distribution of CpGs significant at FDR = 0.05 across 12 blood cell types ",
       x = "Blood cell type", y = "") +
   scale_fill_brewer(palette = "Paired")
```


```{r fig.width = 7, fig.height = 5}
ggplot(sign.pval.df, aes(x = Type, group = Model)) + 
  facet_wrap(~ Model, nrow = 3, scales = "free") +
  geom_bar(aes(y = ..prop.., fill = Model), 
           stat = "count",
          # width = 1,
           position = position_dodge()) + 
  geom_text(aes(label = scales::percent(..prop.., accuracy = 0.1), 
                y = ..prop..), 
            stat = "count", vjust = -0.5, position = position_dodge(1), size = 3) + 
  scale_y_continuous(labels = scales::percent) + 
  labs(x = "Blood cell type", y = "Frequency", 
       title = " ") + 
  theme(legend.title = element_blank(), 
        legend.position = "bottom", 
        panel.grid.major = element_blank(), 
        panel.background = element_blank(), 
        plot.title = element_text(size = 8), 
        axis.title = element_text(size = 8), 
        axis.text.x = element_text(angle = 45, hjust = 0.5)) + 
  scale_fill_manual(values = cbPalette[6:8])

```

```{r}
ggplot(sign.pval.df, aes(x = Type, group = Model, fill = Model)) + 
  geom_density(aes(y = ..prop.., color = Model), 
           stat = "count",
           alpha = 0.2) + 
  scale_y_continuous(labels = scales::percent) + 
  labs(x = "Blood cell type", y = "Frequency", 
       title = " ") + 
  theme(legend.title = element_blank(), 
        legend.position = "bottom", 
        panel.grid.major = element_blank(), 
        panel.background = element_blank(), 
        plot.title = element_text(size = 8), 
        axis.title = element_text(size = 8), 
        axis.text.x = element_text(angle = 45, hjust = 0.5)) 

```


Read TCA baseline models

```{r}
fn.lst  <- list.files("~/bio/code/mpip/dex-stim-human-array/output/data/integrative/cell_type_enrichment/veh/", 
                     pattern = "*RDS", full.names = TRUE)

tca.mdls <- lapply(fn.lst, readRDS)
```

```{r}
tca.mdl   <- lapply(tca.mdls, function(mdl) mdl$tca_mdl)
tca.mu.df <- lapply(tca.mdl, function(mdl) mdl$mus_hat)
tca.mu.df <- do.call(rbind, tca.mu.df) %>% data.frame() %>% setDT(keep.rownames = T) # mean of each BCC type in each CpG

dim(tca.mu.df)
```

```{r}
tca.mu.sign.df <- tca.mu.df[rn %in% sign.pval.df$CpG_ID]
tca.mu.sign.df <- tca.mu.sign.df %>% reshape2::melt() 
colnames(tca.mu.sign.df) <- c("CpG_ID", "Type", "tca_mu_val")

sign.pval.df[, Type := paste0("salas.", Type)]

tca.sign.mu.pval.df <- left_join(sign.pval.df, tca.mu.sign.df)

dim(tca.sign.mu.pval.df)
head(tca.sign.mu.pval.df)
```

```{r}
tca.sign.mu.median.df <- aggregate(tca_mu_val ~ Model + Type, tca.sign.mu.pval.df, median)
# (tca.sign.mu.median.df)

ggplot(tca.sign.mu.median.df, aes(y = tca_mu_val, x = Model, fill = Model)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  scale_fill_viridis(discrete = TRUE, alpha = 0.7, option = "D") +
  facet_wrap(~ Type, ncol = 12) +
  labs(title = " ", y = "Median of all estimates for the mean of each blood cell type in each CpG, veh", x = " ") + 
  theme(legend.position = "bottom", 
        legend.title = element_blank(),
        panel.grid.major = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 10),
        axis.title = element_text(size = 8),
        axis.title.x = element_blank(),
        axis.text.x =  element_blank())
```

Read TCA dex models

```{r}
fn.lst  <- list.files("~/bio/code/mpip/dex-stim-human-array/output/data/integrative/cell_type_enrichment/dex/", 
                     pattern = "*RDS", full.names = TRUE)

tca.mdls <- lapply(fn.lst, readRDS)
```

```{r}
tca.mdl   <- lapply(tca.mdls, function(mdl) mdl$tca_mdl)
tca.mu.df <- lapply(tca.mdl, function(mdl) mdl$mus_hat)
tca.mu.df <- do.call(rbind, tca.mu.df) %>% data.frame() %>% setDT(keep.rownames = T) # mean of each BCC type in each CpG

dim(tca.mu.df)
```

```{r}
pval.dex.fn <- "~/bio/code/mpip/dex-stim-human-array/output/data/integrative/cell_type_enrichment/dnam_cell_type_enrichment_pvals_dex.csv"
pval.dex.df <- fread(pval.dex.fn)

dim(pval.dex.df)

pval.dex.bcc.df <- pval.dex.df[, 1:13]

head(pval.dex.bcc.df)
```

```{r}
fdr.bcc.df <- matrix(p.adjust(as.vector(as.matrix(pval.dex.bcc.df[, 2:13])), method='fdr'), 
                     ncol=12) %>%
  data.frame()

fdr.bcc.df <- cbind(pval.dex.bcc.df$CpG_ID, fdr.bcc.df)
colnames(fdr.bcc.df) <- colnames(pval.dex.bcc.df)
```

```{r}
sign.pval.df <- fdr.bcc.df %>% reshape2::melt(measure.vars = colnames(fdr.bcc.df)[2:13]) %>% setDT()
colnames(sign.pval.df) <- c("CpG_ID", "Type", "fdr")
sign.pval.df <- sign.pval.df[fdr <= 0.05]

sign.pval.df[CpG_ID %in% opposite.fc.cpg.ids$CpG_ID, Model := "opposite_fc"]
sign.pval.df[CpG_ID %in% parallel.fc.delta.ids$CpG_ID, Model := "parallel_fc_delta"]
sign.pval.df[CpG_ID %in% parallel.fc.veh.dex.ids$CpG_ID, Model := "parallel_fc_veh_dex"]

sign.pval.df <- na.omit(sign.pval.df)

tca.mu.sign.df <- tca.mu.df[rn %in% sign.pval.df$CpG_ID]
tca.mu.sign.df <- tca.mu.sign.df %>% reshape2::melt() 
colnames(tca.mu.sign.df) <- c("CpG_ID", "Type", "tca_mu_val")

sign.pval.df[, Type := paste0("salas.", Type)]

tca.sign.mu.pval.df <- left_join(sign.pval.df, tca.mu.sign.df)

dim(tca.sign.mu.pval.df)
head(tca.sign.mu.pval.df)
```

```{r}
tca.sign.mu.median.df <- aggregate(tca_mu_val ~ Model + Type, tca.sign.mu.pval.df, median)
# (tca.sign.mu.median.df)

ggplot(tca.sign.mu.median.df, aes(y = tca_mu_val, x = Model, fill = Model)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  scale_fill_viridis(discrete = TRUE, alpha = 0.7, option = "D") +
  facet_wrap(~ Type, ncol = 12) +
  labs(title = " ", y = "Median of all estimates for the mean of each blood cell type in each CpG, dex", x = " ") + 
  theme(legend.position = "bottom", 
        legend.title = element_blank(),
        panel.grid.major = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 10),
        axis.title = element_text(size = 8),
        axis.title.x = element_blank(),
        axis.text.x =  element_blank())
```
